.docs/CHANGELOG.md
cmd/rpc/server.go
cmd/rpc/web/wallet/components/account.jsx
cmd/rpc/web/wallet/components/api.js
cmd/rpc/web/wallet/components/util.js
controller/fsm.go
fsm/types/error.go
lib/peer.go
lib/tx.go
lib/tx_test.go

Implemented a failure transactions cache on the mempool, to check on failed transactions, added a server endpoint for it and display those transactions in the wallet.
Closes: #4 
- Adds a failed transactions cache to the mempool, which continuously monitors for failed transactions and their accompanied error
- Implemented a `FailedTransactions` endpoint to be consumed by the wallet at the moment
- Display failed transactions on the wallet under the "recent" transactions table
- Fix a minor bug on wallet number formatting which could allow numbers in certain cases
> If a transaction is included in a block - remove it from the cache
Although this is mentioned on the issue, such check is not implemented, my reasoning is that once a transaction has been marked as false, either right away or …

Issue #4 - Failed Transaction cache + display

---

.docs/CHANGELOG.md
cmd/rpc/web/wallet/components/account.jsx
cmd/rpc/web/wallet/components/util.js
cmd/rpc/web/wallet/styles/globals.css

Add max amount form button
Closes: #12 
- Added max amount form button
- Changed `renderForm` function to manage the state internally as an object 
The `renderForm` function may seem to make the object a bit more complex and while its true, it is necessary to allow for react to manage its fields, because the`renderFom` may render different forms with different amount of fields, making use of `useState` per field leads to an `"Error: Rendered more hooks than during the previous render.` if you change to any other form, this new approach allows forms to be of any size without disrupting react rendering and allow for more complex interactions and checks for the future against any kind of form.
(as it can be seem there's a small issue on  `formatNumber` when dealing with decimals, that can be …

Issue-#12: Max amount form button

---

cmd/cli/admin.go
cmd/cli/main.go
cmd/rpc/server.go
lib/crypto/keystore.go
lib/crypto/keystore_test.go

Make password mandatory in backend
Closes: #22
- Make password a mandatory field in `Import` func and update code througout the code for the change.
- Make it a mandatory param in CLI
- [] I have updated documentation (if applicable).
Password was already mandatory in front

feat: make password mandatory also in backend

---

cmd/rpc/web/wallet/components/account.jsx
cmd/rpc/web/wallet/components/util.js
cmd/rpc/web/wallet/pages/index.js

Fixed bug where importing a key does not close the modal after is done and added a loading screen until is shown in the wallet

Issue-#38: close and set import key as main

---

cmd/rpc/web/wallet/.gitignore
cmd/rpc/web/wallet/components/account.jsx
cmd/rpc/web/wallet/components/dashboard.jsx
cmd/rpc/web/wallet/components/governance.jsx
cmd/rpc/web/wallet/styles/globals.css

Applied the weird approach that works on the Governance component to the Accounts component (passing style prop as a string to 'theme' prop, which is the opposite of how that is supposed to work). Also includes a tweak to the dashboard logging control to replace with SVG. 
#78 #86 
Closes: #78 
- Passes style prop as a string value to theme prop of JsonView
- Creates a memoized control button for CanaLog with styled SVGs
- Added supporting styles for the control button
- Added .docker/volumes to .gitignore so that node json files are not suggested as part of commits
The JsonView styles are updating as expected in my testing, but to be honest, the provided styles are ugly and still hard to read. Will likely come back to this and swap out for locally declared styles that match the aesthetic …

Fix for #78 and logging control button tweak

---

cmd/rpc/web/explorer/components/api.js
cmd/rpc/web/explorer/components/cards.jsx
cmd/rpc/web/explorer/pages/index.js

Fixes bug that Next Block Time shows when consensus starts and not when it ends
Closes: #31  
- Add possibility to do config requests in the explorer
- Add consensus duration as state for main page
- Add it to the time for next block time
- Substract it of block time

feat: add consensus duration logic

---

controller/fsm.go

Comment appears to be obsolete - locking not required in this function.

Remove unused comment

---

controller/p2p.go

This fixes a bug where for every locally sent transaction, invalid transactions would still be sent and valid transactions would be sent twice.
Closes: #92
- Removed call to `P2P.SendToPeers()` from `Controller.SendTxMsg`

Fix local transaction gossip issue

---

.docker/volumes/node_1/genesis.json
.docker/volumes/node_2/genesis.json
.docker/volumes/node_3/genesis.json
cmd/cli/admin.go
cmd/rpc/client.go
cmd/rpc/server.go
cmd/rpc/web/wallet/components/account.jsx
cmd/rpc/web/wallet/components/api.js
cmd/rpc/web/wallet/components/svg_icons.jsx
cmd/rpc/web/wallet/components/util.js
controller/result.go
fsm/message_test.go
fsm/swap.go
fsm/swap_test.go
fsm/types/error.go
fsm/types/gov.go
fsm/types/gov.pb.go
fsm/types/message.go
fsm/types/transaction.go
lib/.proto/certificate.proto
lib/.proto/gov.proto
lib/certificate.go
lib/certificate.pb.go
lib/certificate_test.go
lib/error.go
lib/swap.go
lib/swap_test.go

Renames "Buy Orders" to "Lock Orders".
Closes: #96
- Renamed Buy Orders to Lock orders throughout the codebase.

Renaming Buy Orders to Lock Orders

---

cmd/rpc/client.go
cmd/rpc/types.go

Phase 3 of Issue #97.
Client side refactor of RPC transaction types.
Closes: #97
- Monolithic txRequest type split into Tx-specific request types, mirroring how other non-Tx types are implemented.
- Removed single-field struct embeds such as passwordRequest.
- New `fromRequest` and `signerRequest` type created to simplify some handling
- New functions `getFrom` and `getSigner` to simplify some handling, obsoleting old `setFrom` and `setSigner`.
- Submit field moved out of Tx types.
- [] I have run re-built the web-wallet and/or block explorer (if applicable).
- [] I have updated documentation (if applicable).
- [] I have included tests for the changes (if applicable).

txRequest type updates for client.go

---

.docker/Dockerfile
.docker/compose.yaml
Makefile

Who said `Makefiles` can't be pretty? Add multiple miscellaneous enhancements to the `Makefile`
Closes: #137
- Restructured Makefile into logical sections pertaining to what the commands do
- Rename all commands with a prefix of their main purpose
- Add comments to all commands
- Add `help` command which list all the commands and their comments by just typing `make` or `make help`
- Add docker compose command detection for macOS and linux
- Changed the nomenclature off cd'ing to the folder to run the command to each command's native custom directory set
**IMPORTANT:** This "breaks" the current commands as their names changed, please do consult the name changes before anything
```bash
$ make
Usage:
help             print each command's help message
build/canopy     build the canopy binary …
```

Issue-#137: `Makefile` improvements

---

bft/mock_test.go

Fixes inconsistency in how RunVDF is set during tests.

Runvdf config test fix

---

bft/mock_test.go
lib/.proto/p2p.proto
p2p/conn.go
p2p/p2p.pb.go

Add back old ping pong implementation using new `sendProtoMsg` func
Dependency: https://github.com/canopy-network/canopy/pull/144 for unit test fix

feat: add back ping pong

---

cmd/cli/main.go
controller/block.go
fsm/committee.go
lib/crypto/hash.go
lib/error.go
lib/store.go
lib/util.go
store/error.go
store/fuzz_test.go
store/indexer.go
store/smt_test.go
store/store.go
store/store_test.go
store/txn.go
store/txn_test.go
store/wrapper_txn.go
store/wrapper_txn_test.go

Using BadgerDB in **managed mode**, we treat block heights as timestamps. This allows precise versioning of key/value pairs at each block.
- `/State/` – latest state
- `/<PartitionPrefix>/` – historical snapshots (every N blocks)
- `N = 1000`
- `PartitionPrefix = (Height / N) * N` (e.g., 4787 → 4000)
---
On each new write at `LatestHeight`:
- `/State/<Key>` → `Value` @ `LatestHeight`
- `/<PartitionPrefix>/<Key>` → `Value` @ `LatestHeight`
---
If `LatestHeight % N == 1`:
- `LastHeight = LatestHeight - 1`
- For each key in `/State/` at version `LastHeight`:
- Copy to `/<PartitionPrefix>/<Key>` at `LastHeight`
- Delete all older `/State/<Key>` versions
This ensures snapshots are complete for each partition.
---
To read key at `targetBlock`:
```go
txn := db.NewTransactionAt(targetBlock)
if …
```

Partition DB Design

---

controller/consensus.go

This PR updates the node syncing functionality in `controller/consensus.go` to optimize synchronization and handle unexpected blocks.
- Implements a queue to track both block requests sent and block request responses awaiting processing by the FSM.
- A new type `blockSyncRequest` was created to track these requests in the queue.
- Block requests are distributed randomly to all known peers in the PeerSet.
- Uses the SimpleLimiter to limit requests per node to avoid rate limiting and reputation slashing.
- A `rateScaleFactor` setting to allow node runners to increase or decrease their block request rates
- Gracefully handles (ignores and prints warning) when the latest gossiped block is received.
Issue: #131

Issue #131 - Node Sync Optimization

---

controller/consensus.go

This PR addresses the following:
- blockRequest timestamp initialization
- Panic due to missing lock around `HandlePeerBlock`
- One sufficiently long `processQueue` times, block requests could timeout when they shouldn't

Node Sync Fixes

---

cmd/rpc/sock.go

Allow multiple subscribers per `ChainID` to ws updates
Closes: #164 
- Modified `RCManager` so each chain could have multiple subscribers

Issue-#164:  Allow multiple subscribers per `ChainID` to ws updates

---

.docker/Dockerfile
.docker/compose.yaml
.github/workflows/release.yml
.gitignore
Dockerfile
Makefile
auto-update/Dockerfile
auto-update/README.md
auto-update/main.go
cmd/cli/admin.go
cmd/cli/cli.go
cmd/cli/query.go
cmd/main/main.go
lib/config.go

Add auto update main.go process to handle updates on new releases of canopy
Closes: #162 
- Add cli package on cmd to separate the main.go file to its own package, this to be able to import vars from it in the auto update package.
- Change config setup to be when canopy software starts.
- Add auto update flag to the config.
- Add auto update mechanism to check for updates on the official github repo of canopy network
- Add Dockerfile on example on how to deploy it
- Update makefile to new binary location
- Add action to create release in github and add binaries
- [] I have included tests for the changes (if applicable).
Current .docker dir was just updated to the new location of the main binary not using the auto update since its main purpose is for testing development versions

feat: implent auto update

---

auto-update/main.go
cmd/rpc/server.go

- Add atomic bool to control when kill signal is sent from child
- Get logging a bit better
- Use continues instead of returns where needed

fix: make auto update to not send kill to child when child fied first

---

lib/config.go

-Fix spelling on P2P config of the json tag
Note: config jsons of testing tags were already using the correct spelling
Closes #225

fix: spelling on trusted peer ids in config

---

cmd/cli/cli.go
controller/consensus.go
lib/metrics.go
p2p/set.go

- Add `canopy_chain_id` and `canopy_sofware_version` metrics that are just updated on start up of the node
- Change `canopy_block_num_txs` to a Gauge that resets in each block
- Change `canopy_syncing_status` to 1 for synced and 0 for syncing since synced is the healthy status
- Fix `canopy_validator_status` to actually fullfil the values in help `Validator status (0: Unstaked, 1: Staked, 2: Unstaking, 3: Paused)`
- Change `canopy_peer_total` to be updated to the added up value of inbound and outbound peers so it shows the same value as the wallet
- Add `canopy_startup_block` metric to save the block where a node started
Closes #229

Fix metrics

---

.docker/Dockerfile
Dockerfile
lib/config.go
store/store.go

BadgerDB's `DropPrefix` feature is pretty slow and may even block writes in some occasions, this makes the eviction process to block for a long time which could even cause nodes to miss consensus, this improves the eviction process by having a dynamic LSS store prefix that changes on every eviction, and defer the `DropPrefix` method itself to a goroutine.
This even makes the store safer because the new prefix is never used until its changes have been committed so if for some reason that fails, the whole eviction process will stop and the previous prefix will continue to be used, leaving the store now with no dangers of data loss during eviction.
Closes: #<issue-number>
- Update go docker image to 1.24 (needed for build reasons)
- Improve eviction process to make `DropPrefix` async
- …

Eviction Improvement
