.docs/CHANGELOG.md, cmd/rpc/web/wallet/components/api.js
Fix wallet issue where received transactions do not show `included`
Closes: #23 
- Fix wallet issue
=> #Issue-#23: fix: received transactions contains no status

.docs/CHANGELOG.md, .gitignore, cmd/rpc/web/wallet/components/api.js, cmd/rpc/web/wallet/components/navbar.jsx, cmd/rpc/web/wallet/pages/index.js, cmd/rpc/web/wallet/styles/globals.css
Display latest height in wallet 
Closes: #5 
- Display latest height in wallet
=> Issue-#5: [Wallet] latest `height`

.docs/CHANGELOG.md, cmd/rpc/web/wallet/components/account.jsx
Add more validator status to wallet 
Closes: #9
- Add more validator status to wallet
=> Issue-#9: add more validator status to wallet

.docs/CHANGELOG.md, cmd/rpc/web/wallet/components/account.jsx, cmd/rpc/web/wallet/components/form_inputs.jsx, cmd/rpc/web/wallet/components/governance.jsx, cmd/rpc/web/wallet/components/util.js, cmd/rpc/web/wallet/styles/globals.css
Refactored all the form input handling code and consolidate all the forms to use the same component
Closes: #45 
- I changed `param value` to a `number` input as all the parameters but `protocol version` are numbers and I doubt that a proposal will be made through the UI to only change the protocol version but do let me know if you want this reverted.
=> Issue #45: Fix Wallet governance forms

cmd/rpc/web/wallet/components/account.jsx, cmd/rpc/web/wallet/components/governance.jsx
Fixes the bug where when clicking`Submit Proposal` the accordion does not close
Closes: #41
=> Issue-#41: Proposal submit does not close accordion

cmd/rpc/web/wallet/components/account.jsx, cmd/rpc/web/wallet/components/util.js
Implements a button to dowload the `Keystore`
Closes: #6
=> Issue-#6: download keystore button

cmd/rpc/web/wallet/components/governance.jsx, cmd/rpc/web/wallet/components/util.js
Fix issue trying to vote on the default placeholders throwing an error 
Closes: #37
- Fix issue trying to vote on the default placeholders throwing an error 
- Add a safeguard option for JSON inputs to prevent invalid JSON
=> Issue-#37: default proposals textbox throw error

cmd/rpc/web/wallet/components/account.jsx
Switch account when selecting another node in form
Closes: #64
- Fix the issue when selecting another account in the wallet forms did not change the max value
- Actual change happens in lines 143-146, everything else was the linter running again as the file had inconsistent spacing
- Selecting the account on the form will also make it the default one on the main page, not sure whether that is the desired behavior
=> Issue-#64 - Switch account in form bug

cmd/rpc/web/wallet/components/account.jsx, cmd/rpc/web/wallet/components/canaJSON.jsx, cmd/rpc/web/wallet/components/governance.jsx, cmd/rpc/web/wallet/styles/globals.css
Added a bespoke JSON viewer for the Canopy UI
Closes: #90 
- Removed JsonView component
- Created bespoke CanaJSON component
- Modified toast CSS to set the width to auto to allow for longer toast messages without it all getting squished up
- Removed outline-danger class from Submit Transaction button in Send function.
n/a
=> ** Added CanaJSON component **

cmd/rpc/web/wallet/components/governance.jsx, cmd/rpc/web/wallet/styles/globals.css
Fixes issue where the carrousel on the governance tab is displayed incorrectly under certain zoom level or display sizes
Closes: #119 
https://github.com/user-attachments/assets/fcdf1fa7-ea1b-4d6a-9509-136d677394f6
=> Issue-#119: Governance carrousel displayed incorrectly at certain sizes

cmd/rpc/web/wallet/components/canaJSON.jsx, cmd/rpc/web/wallet/components/governance.jsx
Corrected state call in Governance view and added event prevention to the CanaJSON component.
Closes: #120 
See description
IT IS FINALLY DEBUGGED.
=> Tweaks on the JSON component and correcting the state call

bft/bft.go, lib/.proto/p2p.proto, p2p/book_test.go, p2p/conn.go, p2p/encrypt.go, p2p/encrypt_test.go, p2p/error.go, p2p/p2p.go, p2p/p2p.pb.go, p2p/p2p_test.go, p2p/set_test.go
PR just for visibility of test deploy
=> feat: change P2P handle send message logic

bft/bft.go, cmd/cli/main.go, cmd/rpc/query_handlers.go, cmd/rpc/routes.go, cmd/rpc/types.go, cmd/rpc/web/explorer/components/api.js, cmd/rpc/web/explorer/components/cards.jsx, controller/controller.go, fsm/committee.go, fsm/committee_test.go, lib/error.go
Creates an economic parameters endpoint that provides the following:
- Mint per block
- Mint per committee
- DAO cut
- Block proposer cut
- Delegate cut
Explorer updated to dynamically update the minted CNPY per block.
Closes: #105
=> Economic Parameters endpoint

p2p/README.md
Documentation of P2P as markdown
#126 
Add readme to p2p package
=> feat: add first version of p2p readme doc

fsm/committee.go, fsm/genesis.go, fsm/message.go, fsm/message_helpers.go, fsm/validator.go, lib/consensus.go, lib/crypto/eth_secp256k1.go, lib/crypto/secp256k1.go
=> issue-#179

.docker/Dockerfile, p2p/conn.go, p2p/p2p.go, p2p/p2p_test.go
- Fix panic on race condition of sends in closed channels.
- Update go version in docker
=> fix: closed channel panic race conditon and update docker

cmd/rpc/client.go, cmd/rpc/types.go
This field erroneously removed in a previous PR.
=> Added Submit field back to some transaction requests

auto-update/main.go
Add read before close in config for auto update.
=> fix: add write file before closure so nothing is delete

cmd/rpc/sock.go, p2p/book.go
Simple PR to fix two reported panics from peer issues
=> Fix: Peer issues

cmd/rpc/web/explorer/components/cards.jsx, cmd/rpc/web/explorer/components/modal.jsx, cmd/rpc/web/explorer/components/table.jsx, cmd/rpc/web/explorer/pages/index.js, cmd/rpc/web/explorer/styles/globals.css, cmd/rpc/web/wallet/components/account.jsx, cmd/rpc/web/wallet/components/governance.jsx, cmd/rpc/web/wallet/pages/index.js
=> closes Issue #212
